name: Build and Publish Python Package

on:
  workflow_dispatch:
  push:
    branches:
      - "*"
  release:
    types:
      - created

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[test]

      - name: Run tests
        run: |
          pytest

  build:
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Build package
        run: |
          python -m pip install --upgrade pip
          pip install build
          python -m build -w

      - name: Upload wheel
        uses: actions/upload-artifact@v4
        with:
          name: simple-image-gallery
          path: dist/*.whl

  private-publish:
    needs:
      - build
    runs-on: ubuntu-latest

    steps:
      - name: Download wheel
        uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true

      - name: Connect to Tailnet
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
          version: latest
          use-cache: 'true'

      - name: Publish to private PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: ${{ secrets.PYPI_USER }}
          password: ${{ secrets.PYPI_PWD }}
          repository-url: ${{ vars.PYPI_URL }}
          packages-dir: dist
          attestations: false
          verbose: true

  public-publish:
    needs:
      - build
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'release' && github.event.action == 'created' }}
    environment:
      name: pypi
      url: https://pypi.org/p/simple-image-gallery
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - name: Download wheel
        uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist
          verbose: true